<?php
/**
* @file
* Implements various blocks to improve pending content workflow.
*/
/**
* Implements hook_block_info().
*/
/*function custom_indexpage_block_info() {
  $blocks['judgments'] = array(
    'info' => t('Judgments'),
  );
  //$blocks['legislation'] = array(
   // 'info' => t('Legislation'),
  //);
  
  return $blocks;
} */

function custom_indexpage_menu() {
 
  $aItems = array(
      'custom_indexpage' => array(
        'title' => 'Custom Index page',
        'page callback' => 'custom_indexpage_view',
        'access callback' => TRUE,
        'access arguments' => array('access custom_indexpage'),
        'type' => MENU_NORMAL_ITEM,
      ),
    );
  return $aItems;
}


/**
 * Implements hook_block_view().
 */
function custom_indexpage_view($delta = '') {

  //$t = get_t();
  $content = array();
  
  //echo current_path();
  $path_ar = explode('/',current_path());
  $linktype = $path_ar[1];
 
  $title = $linktype;
  if($linktype == 'cmac_award'){
    $title = "Conciliation Mediation and Arbitration Commission";
  }
  drupal_set_title($title);

  if(isset($linktype)){
   
    
    $result = db_query("SELECT n.title FROM {node} n WHERE n.type = '$linktype' ");

   
    $num = $result->rowCount();

    
    
     $sqlresult = db_query("SELECT SUBSTRING(nd.title,1,1) AS letter,nd.title FROM {node} nd 
    WHERE nd.type = '$linktype' ORDER BY nd.title ");

    $alpha = array();

    foreach($sqlresult as $letters){
      $alpha[$letters->letter] = $letters->title;
    }

      if($num > 0){
      
          $titles = '';
          foreach ($result as $row) {
            $titles .= $row->title.'<br />';
          }

          //$lists = '<p>Database last updated: '. $created .'</br>';
          $lists = '<p>';
        
          $lists .= 'Alphabetical Index:</p>';        
          $word = '<p></p>';
          foreach(range('A','Z') as $i) {         
          $word .= (array_key_exists ("$i", $alpha)) ? t('<a href="@url">'.$i.'</a>', array('@url' => url('custom_indexlist/'.$linktype.'/'.strtolower($i)))) : "$i";
          $word .= ($i != 'Z') ? ' | ':'';
          }        

          if($linktype == 'cmac_award'){
            $years_range = '<p></p>';
            $years_range .= '<p>Decisions beginning with:</p>';

            $result = db_query("SELECT adate.field_awarddate_value
              FROM {field_data_field_awarddate} adate  WHERE adate.bundle ='$linktype' ");

            $date_year = array();

            foreach($result as $ad){
                $yearval = date('Y', strtotime($ad->field_awarddate_value));
                if(!in_array($yearval,$date_year)){
                   $date_year[] = $yearval;
                }
                 
            }//end of foreach
            sort($date_year);
            foreach($date_year as $year) {
              //$years_range .= "<a href='/custom_indexlist=$linktype&year=$year'>| $year </a> ";
              $years_range .=  t('<a href="@url">'.$year.' | </a>', array('@url' => url('custom_indexlist/'.$linktype.'/'.$year)));

            }

      }
      $content['content'] = array(
          '#type' => 'fieldset',
          '#description'=>t($lists.$word.$years_range),
          //'#description'=>t($lists.$word.$years_cont.$years_range),
      );
    }
    else{
       $content['content'] = array(
      '#type' => 'fieldset',
      '#description'=>t("<strong>There are currently no Court Rolls added</strong>"),
      );
    }
   
    
  }
  return $content;
}


function content_beginwith() {


  //Code added for fixing the url-path
  $path_ar = explode('/',current_path());
  $legtype = $path_ar[1];
  $letter = strtoupper($path_ar[2]);

  $legisname = db_query("SELECT name FROM {node_type} WHERE type = '$legtype' ")->fetchField();
  //$courtname = str_replace('-',' ',$passedcourtname);
  //$courtname = ucwords($courtname);
  drupal_set_title($legisname .' beginning with '.$letter);

  $queryres=db_query("SELECT nd.title, ualias.alias
  FROM {node} nd INNER JOIN {url_alias} ualias ON
  ualias.source = CONCAT('node/',nd.nid) 
  AND nd.title LIKE '$letter%'
  AND nd.type = '$legtype' ");


  $data = '<p><strong>type:</strong> judgment';
  $data .= '<p><strong>database:</strong> '.$legisname;
  $data .= '<p><strong>alpha:</strong> '.$letter;
  $data .= "<p><ul>";
  foreach($queryres as $result){
    $content_title = $result->title;
    $content_src = $result->alias;
    //$data .="<li><a href='$content_src'>$content_title</a></li>"; 
    $data .= t('<li><a href="@url">'.$content_title.'</a></li>', array('@url' => url($content_src)));
  }
  $data .= "</ul></p>";

  $content['content'] = array(
    '#type' => 'fieldset',
    '#description'=>t($data),
  );
  return $content;
  
  
}