<?php
/**
 * Implements hook_menu()
 * @return array
 */
function consol_leglistyear_menu() {
 
  $aItems = array(
      'consol_leglistyear' => array(
        'title' => 'Consolidated Legislation Year List',
        'page callback' => '_page_consol_leglistyear',
        //'access callback' => TRUE,
        'access arguments' => array('access consol_leglistyear'),
        'type' => MENU_NORMAL_ITEM,
      ),
    );
  return $aItems;
}
 
/**
 * Page callback mapped to the url /hello_world
 *
 * @return array
 */
function _page_consol_leglistyear() {
    $content = array();
    $legname = '';
    $year = '';
    if(isset($_GET['legname']) && isset($_GET['year'])){
      $legname = $_GET['legname'];
      $year = $_GET['year'];
    }
    //echo $courtname;exit;
    
    drupal_set_title($legname.' classified with '.$year);
    $metadata = '<p><strong>type:</strong>Legislation';
    $metadata .= '<p><strong>database:</strong>'.$legname;
    $metadata .= '<p><strong>year:</strong>'.$year;

    if($legname == "Legislation as promulgated"){      
      $type = "legislation_promulgated";
      $result = db_query("SELECT n.title,pdate.field_yearact_value,ualias.alias FROM {node} n     
        INNER JOIN {field_data_field_yearact} pdate
        ON n.nid = pdate.entity_id
        AND pdate.field_yearact_value = '$year'
        INNER JOIN {url_alias} ualias
        ON CONCAT('node/',n.nid) = ualias.source
        ORDER BY n.title ");

      $date_month = array();
      

      $date_ar = array();  
      $titles = '<p><ul>';  
      $prev_month = "";
     
      foreach($result as $res){        
        $alias = $res->alias;
        $titles .= '<li>'."<a href='$alias'>".$res->title.'</a></li>';        
      }// End of for loop
      
      $titles .= '</ul></p>';
      
      $content['content'] = array(
        '#type' => 'fieldset',
        '#description'=>t($metadata.$titles),
      );
    }
    else if($legname == "Consolidated Legislation"){      
      $type = "consolidated_legislation";
      $result = db_query("SELECT n.title,cdate.field_consoldate_value,ualias.alias FROM {node} n     
        INNER JOIN {field_data_field_consoldate} cdate
        ON cdate.entity_id = n.nid 
        INNER JOIN {url_alias} ualias
        ON CONCAT('node/',n.nid) = ualias.source
        WHERE n.type = '$type' ORDER BY n.title ");

      $date_month = array();
      

      $date_ar = array();  
      $months = '<p></p>';
      $titles = '<p><ul>';  
      $prev_month = "";
     
      foreach($result as $res){        
        $alias = $res->alias;
        if(date('Y',strtotime($res->field_consoldate_value)) == $year){
          $titles .= '<li>'."<a href='$alias'>".$res->title.'</a></li>'; 
        }
               
      }// End of for loop
      
      $titles .= '</ul></p>';
      
      $content['content'] = array(
        '#type' => 'fieldset',
        '#description'=>t($metadata.$months.$titles),
      );
    }

    else if($legname == "Subordinate Legislation"){      
      
      $type = "subordinate_legislation";
      $result = db_query("SELECT n.title,subyear.field_sublegyear_value,ualias.alias FROM {node} n     
        INNER JOIN {field_data_field_sublegyear} subyear
        ON subyear.entity_id = n.nid 
        AND subyear.field_sublegyear_value = '$year'
        INNER JOIN {url_alias} ualias
        ON CONCAT('node/',n.nid) = ualias.source
        ORDER BY n.title ");

      $date_month = array();
      

      $date_ar = array();  
      $months = '<p></p>';
      $titles = '<p><ul>';  
      $prev_month = "";
     
      foreach($result as $res){        
        $alias = $res->alias;
          $titles .= '<li>'."<a href='$alias'>".$res->title.'</a></li>';        
      }// End of for loop
      
      $titles .= '</ul></p>';
      
      $content['content'] = array(
        '#type' => 'fieldset',
        '#description'=>t($metadata.$months.$titles),
      );
    }
    return $content;

    //return array(
      //'#markup' => '<p>Consol Legislation</p>',
    //);
  
}

