<?php
/**
 * Implements hook_menu()
 * @return array
 */
function courtsmenu_menu() {
 
  $aItems = array(
      'courtsmenu' => array(
        'title' => 'Judgments',
        'page callback' => '_courts_menu',
        'access callback' => TRUE,
      ),
    );
  return $aItems;
    
}
 
/**
 * Page callback mapped to the url /hello_world
 *
 * @return array
 */
function _courts_menu() {
  //return array(
    //'#markup' => '<p>Hello world</p>'
  //);
  
  $t = get_t();

  $courtname = '';
  $type = 'courtnamesadd';


  $result = db_query("SELECT title FROM {node} WHERE type = :type",array(':type' => $type,));

  foreach ($result as $row) {
    
    $name = $row->title; 
   
    //$courtname .= "<a href='/courtnames&courtname=$name'>".$name."</a><br/>";

    $trimmednm = str_replace(' ','-',$name);
    $newname = trim(strtolower($trimmednm));
    $courtname .= $t('<a href="@url">'.$name.'</a>', array('@url' => url('courtnames/'.$newname))) . "<br/>" ;
  

  }


  $judgments = '<p><br />'.$courtname .'</p>';
  
  $content['content'] = array(
        '#type' => 'fieldset',
        '#description'=>t($judgments),
      );
    return $content;


  //return array(
    //'#markup' => '<p>Hello world</p>'
  //);


 
}

