<?php

	require_once('judgment_functions.inc');
	/**
	* Implements hook_node_info().
	*/
	function judgment_node_info() {

		$items = array();
		$items['judgment'] = array(
			'name' => t('Judgment Content Type'),    // name of your content type
			'type' => 'judgment',
			'base' => 'node_content',
			'description' => t('A content type to handle judgments.'),
			'has_title' => 1,
			'title_label' => t('Judgment Title'),
			'body_label' => t('Judgment Description'),
			//'help' => t('Please fill in all fields.'),
			'custom' => TRUE,
		);
		return $items;
	}

	function judgment_form($node, $form_state) {
		/*$title = $node->title;
		$nid = $node->nid;

		$form = array();
  		$type = node_type_get_type($node);

		if($node->type == 'judgment'){
			$result = db_query("SELECT jdate.field_jdate_value,case.field_casenumber_value FROM {field_data_field_casenumber} case 
	    	INNER JOIN {field_data_field_jdate} jdate ON case.entity_id = $nid WHERE jdate.entity_id = $nid ");

			$record = $result->fetchObject();
			$title .= $record->field_casenumber_value;
			$title .= $record->field_jdate_value;
			$form_state['values']['title'] = $title;
		}*/
		//print_r($node);
		return node_content_form($node, $form_state);
	}
	
	
?>

