<?php
/**
 * Implements hook_menu()
 * @return array
 */
function helloworld_menu() {
 
  $aItems = array(
      'hello_world' => array(
        'title' => 'Hello world',
        'page callback' => '_page_hello_world',
        'access callback' => TRUE,
      ),
    );
  return $aItems;
}
 
/**
 * Page callback mapped to the url /hello_world
 *
 * @return array
 */
function _page_hello_world() {
  //return array(
    //'#markup' => '<p>Hello world</p>'
  //);

  $bundle = 'courtnames';
  $mnc_code = 'scza';
  

  $count = db_query("SELECT * FROM {field_revision_field_courtname} WHERE bundle = :bundle",array(':bundle' => $bundle,))->rowCount();
  //$count = $result->rowCount();

  $countries = country_get_list();
  $cnt = variable_get('site_default_country');
  //print_r($countries);
  echo $cnt;
  
  $content = array();
  $content['content'] = array(
        '#type' => 'fieldset',
        '#description'=>t($count),
      );

  if($count > 0){
   
      $modules = array('judgment'); // Array of module names
      $enable_dependencies = TRUE;
      module_enable($modules, $enable_dependencies);
  }
  


  return $content;

  /*$form = array();
  # the values for the dropdown box
$form['type_options'] = array(
  '#type' => 'value',
  '#value' => array('APPLICATION' => t('Application'),
                    'DEVELOPMENT' => t('Development'),
                    'ENHANCEMENT' => t('Enhancement'))
);
$form['type'] = array(
  '#title' => t('Project Type'),
  '#type' => 'select',
  '#description' => "Select the project count type.",
  '#options' => $form['type_options']['#value'],
);

 $form['onthisdate_maxdisp'] = array(
    '#type' => 'textfield',
    '#title' => t('Maximum number of links'),
    '#default_value' => variable_get('onthisdate_maxdisp', 3),
    '#size' => 2,
    '#maxlength' => 2,
    '#description' => t("The maximum number of links to display in the block."),
    '#required' => TRUE,

  );
 
return $form;*/
}

