<?php 
/**
 * Implements hook_menu()
 * @return array
 */

require_once('courtnames_functions.inc');

function courtnames_menu() {
 //$courtname = $_GET['courtname'];
  $aItems = array(
      'courtnames' => array(
        'title' => 'Court names',
        'page callback' => '_page_courtnames',
        'access callback' => TRUE,
      ),
    );
  return $aItems;
}
 
/**
 * Page callback mapped to the url /courtnames
 *
 * @return array
 */
function _page_courtnames() {
  $content = array();
  $courtname = '';
  if(isset($_GET['courtname'])){
    $courtname = $_GET['courtname'];
  }
  //echo $courtname;exit;
  drupal_set_title($courtname);
  $type = 'judgment';
  $mnc_code = 'scza';
  $result = db_query("SELECT * FROM {node} WHERE type = :type",array(':type' => $type,));

  $result2 = db_query("SELECT jdate.field_jdate_value FROM {field_revision_field_issuingcourt_select} issuingcourt INNER JOIN {field_data_field_jdate} jdate
                         ON issuingcourt.entity_id = jdate.entity_id 
                         WHERE issuingcourt.field_issuingcourt_select_value LIKE '%$courtname%' ");  


  $date_ar = array();
  $date_year = array();
  foreach($result2 as $dt){

    $date_ar[] = date('j F Y',strtotime($dt->field_jdate_value)).'<br/>';
    $yearval = date('Y',strtotime($dt->field_jdate_value));
    if(!in_array($yearval,$date_year)){
      $date_year[] = $yearval;
    }
    
  }
  $num = count($date_ar);



  //query to extract the first letter of the judgment
  $sqlresult = db_query("SELECT SUBSTRING(nd.title,1,1) AS letter,nd.title, issuingcourt.field_issuingcourt_select_value FROM {node} nd INNER JOIN { field_data_field_issuingcourt_select} issuingcourt ON 
  nd.nid = issuingcourt.entity_id WHERE issuingcourt.field_issuingcourt_select_value LIKE '%$courtname%' ORDER BY nd.title ");
  
  $alpha = array();

  foreach($sqlresult as $letters){
    $alpha[$letters->letter] = $letters->title;
  }


  if($num > 0){
      //echo "TEST";exit;   
      $created = min($date_ar);
          
      $titles = '';
      foreach ($result as $row) {
        $titles .= $row->title.'<br />';
      }

      //$content['titles'] = $titles;
      $lists = '<p>Most recent decision: '. $created .'';
      $lists .= 'Number of decisions: '. $num .'<br/>';
      $lists .= 'Decisions beginning with:</p>';

      
      $word = '<p></p>';
      foreach(range('A','Z') as $i) {
        $word .= (array_key_exists ("$i", $alpha)) ? "<a href='courtbeginning?letter=$i&courtname=$courtname'".">".$i."</a>" : "$i";
        $word .= ($i != 'Z') ? ' | ':'';
        /*if(in_array($i,$alpha)){
          $word .= "< a href='courtbeginning?letter='> $i </a>"; 
        }*/
      }

      $query3 = "select distinct from_unixtime(field_jdate_value, '%Y') as year from content_type_caselaw where field_mnc_value like '%$mnc_code%' order by field_jdate_value";

      $years_cont = '<p></p><p>Decisions for the years:</p>';

      sort($date_year);
      $years_range = '<p></p>';
      foreach($date_year as $year) {
          $years_range .= "<a href='courtdecisions?courtname=$courtname&year=$year'>| $year </a> ";
      }

      $content['content'] = array(
        '#type' => 'fieldset',
        '#description'=>t($lists.$word.$years_cont.$years_range),
      );
  }
  else{
    $content['content'] = array(
    '#type' => 'fieldset',
    '#description'=>t("<strong>There are currently no judgments loaded for this court</strong>"),
    );
  }
  
return $content;



}

