<?php

	function other_node_info() {

		$items = array();
		$items['other'] = array(
			'name' => t('Other Content Type'),    // name of your content type
			'type' => 'other',
			'base' => 'node_content',
			'description' => t('A content type to handle government gazette.'),
			'has_title' => 1,
			'title_label' => t('Title'),
			'body_label' => t('Description'),
			//'help' => t('Please fill in all fields.'),
			'custom' => TRUE,
		);
		return $items;
	}

	function other_form($node, $form_state) {
	
		return node_content_form($node, $form_state);
	}
?>
