<?php
/**
 * Implements hook_menu()
 * @return array
 */
function journalarticlebeginwith_menu() {
 
  $aItems = array(
      'journalarticlebeginwith' => array(
        'title' => 'Articles beginning with',
        'page callback' => '_page_journalarticlebeginwith',
        //'access callback' => TRUE,
        'access arguments' => array('access journalarticlebeginwith'),
        'type' => MENU_NORMAL_ITEM,
      ),
    );
  return $aItems;
}
 
/**
 * Page callback mapped to the url /hello_world
 *
 * @return array
 */
function _page_journalarticlebeginwith() {
  //return array(
    //'#markup' => '<p>Hello world</p>'
  //);
      $letter = '';
      $courtname = '';
      if(isset($_GET['letter']) && isset($_GET['journalname'])){
        $letter = $_GET['letter'];
         $jname = $_GET['journalname'];
      }
      
      drupal_set_title('Journal Articles beginning with'.' '.$letter);

      $queryres=db_query("SELECT nd.title, ualias.alias, jtitle.field_journaltitle_select_value 
      FROM {node} nd INNER JOIN {field_data_field_journaltitle_select} jtitle ON 
      nd.nid = jtitle.entity_id
      INNER JOIN {url_alias} ualias ON
      ualias.source = CONCAT('node/',nd.nid) 
      AND nd.title LIKE '$letter%'
      AND jtitle.field_journaltitle_select_value LIKE '%$jname%'
      AND nd.type = 'journal' ");


      $data = '<p><strong>type:</strong> journal';
      $data .= '<p><strong>database:</strong> '.$jname;
      $data .= '<p><strong>alpha:</strong> '.$letter;
      $data .= "<p><ul>";
      foreach($queryres as $result){
        $content_title = $result->title;
        $content_src = $result->alias;
        $data .="<li><a href='$content_src'>$content_title</a></li>"; 
      }
      $data .= "</ul></p>";

      $content['content'] = array(
        '#type' => 'fieldset',
        '#description'=>t($data),
      );
      return $content;

 
}

