<?php
/**
 * Implements hook_menu()
 * @return array
 */


function itemhide_block_info_alter(&$blocks, $theme, $code_blocks) {
  // Example - disallow access for anonymous to node 15 from custom module
  global $user;
  if (DRUPAL_ANONYMOUS_RID) {
    $blocks['system']['navigation']['status'] = 0;//'_acccessCheck';
    //$blocks['title'] = '<node>';
  }
  else{
    $blocks['system']['navigation']['status'] = 1;
    $blocks['title'] = '<none>';
  }

}



function _allowAccess($string, $account = NULL){  
    global $user;

    if (!isset($account)) {
      $account = $user;
    }

    // User #1 has all privileges:
    if ($account->uid == 1) {
      return TRUE;
    }
    

    // To reduce the number of SQL queries, we cache the user's permissions
    // in a static variable.
    // Use the advanced drupal_static() pattern, since this is called very often.
    static $drupal_static_fast;
    if (!isset($drupal_static_fast)) {
      $drupal_static_fast['perm'] = &drupal_static(__FUNCTION__);
    }
    $perm = &$drupal_static_fast['perm'];
    if (!isset($perm[$account->uid])) {
      $role_permissions = user_role_permissions($account->roles);

      $perms = array();
      foreach ($role_permissions as $one_role) {
        $perms += $one_role;
      }
      $perm[$account->uid] = $perms;
    }

    return isset($perm[$account->uid][$string]); 
}
