<?php
/**
 * Implements hook_menu()
 * @return array
 */
function bulkuploadfiles_menu() {
 
  $aItems = array(
      'bulkuploadfiles' => array(
        'title' => 'Bulk Upload Files',
        'page callback' => '_page_bulkuploadfiles',
        //'access callback' => TRUE,
        'access arguments' => array('access bulkuploadfiles'),
        'type' => MENU_NORMAL_ITEM,
      ),
    );
  return $aItems;
}
 
/**
 * Page callback mapped to the url /hello_world
 *
 * @return array
 */
function _page_bulkuploadfiles() {
  //$uploadpage = file_get_contents('/node/add/uploadfiles');
  $goto = drupal_goto("node/add/uploadfiles");
  return array(
    '#markup' => $goto
  );

  
  //return $content;

  
}

