<?php
/**
 * Implements hook_menu()
 * @return array
 */
function legislation_display_menu() {
 
  $aItems = array(
      'legislation_display' => array(
        'title' => 'Display Legislation',
        'page callback' => '_page_legislation_display',
        //'access callback' => TRUE,
        'access arguments' => array('access legislation_display'),
        'type' => MENU_NORMAL_ITEM,
      ),
    );
  return $aItems;
}
 
/**
 * Page callback mapped to the url /hello_world
 *
 * @return array
 */
function _page_legislation_display() {

  drupal_set_title("");
  if(isset($_GET['frbr_uri'])){
    $frbr_uri = $_GET['frbr_uri'];
  }
  return file_get_contents('http://indigo.code4sa.org/api'.$frbr_uri.'/eng.html');

}

