<?php
/**
 * Implements hook_menu()
 * @return array
 */
function consol_leglist_menu() {
 
  $aItems = array(
      'consol_leglist' => array(
        'title' => 'Legislation',
        'page callback' => 'legislation_output',
        'access callback' => TRUE,
        'access arguments' => array('access consol_leglist'),
        'type' => MENU_NORMAL_ITEM,
      ),
    );
  return $aItems;
}
 


function legislation_output() {

    $content = array();
    $path = current_path();
    $path_ar = explode('/',$path);
    $letter = $path_ar[2];
    $letter_size = strlen($letter);
//print_r($path_ar);
    //echo count($path_ar);
    if(count($path_ar) == 3 && ($letter_size !=1 && $letter_size !=4)){

      return _page_consol_leglist($path);
    }
    else{
      return legislation_beginwith($path);
    }
    
}


/**
 * Page callback mapped to the url /consol_leglist
 *
 * @return array
 */
function _page_consol_leglist($current_path) {


  $content = array();
  
  //$path_ar = explode('/',current_path());
  $path_ar = explode('/',$current_path);
  //print_r($path_ar);
  $legtype = $path_ar[1];
  $legname = $path_ar[2];

  //if($legname == "Consolidated Legislation"){
  if($legtype == "consolidated_legislation"){
    $legname = str_replace('-',' ',$legname);
    $legname = ucwords($legname);
 
    drupal_set_title($legname);
    
    $result = db_query("SELECT n.title FROM {node} n WHERE n.type = '$legtype' ");

    $result2 = db_query("SELECT cdate.field_consoldate_value FROM {field_data_field_consoldate} cdate  WHERE cdate.bundle ='$legtype' ");  

    $query2=db_query("SELECT DATE_FORMAT(cdate.field_consoldate_value,'%d %M %Y')
      FROM {field_data_field_consoldate} cdate  WHERE cdate.bundle ='$legtype' ")->fetchCol();

    //print_r($result);exit;
    $date_ar = array();
    $date_year = array();
    foreach($result2 as $dt){

      $date_ar[] = date('j F Y',strtotime($dt->field_consoldate_value)).'<br/>';

      $year_val = date('Y',strtotime($dt->field_consoldate_value));
      if(!in_array($year_val,$date_year))
        $date_year[] = $year_val;
    }
    $num = $result->rowCount();

    $consoldate_num = $result2->rowCount();
    //query to extract the first letter of the judgment

    if($consoldate_num > 0){
      $sqlresult = db_query("SELECT SUBSTRING(nd.title,1,1) AS letter,nd.title, cdate.field_consoldate_value FROM {node} nd INNER JOIN {field_data_field_consoldate} cdate ON 
    nd.nid = cdate.entity_id WHERE cdate.bundle = '$legtype' ORDER BY nd.title ");
    }
    else{
      $sqlresult = db_query("SELECT SUBSTRING(nd.title,1,1) AS letter,nd.title FROM {node} nd 
    WHERE nd.type = '$legtype' ORDER BY nd.title ");
    }
    
    
    $alpha = array();

    foreach($sqlresult as $letters){
      $alpha[$letters->letter] = $letters->title;
    }


    if($num > 0){
        //$ind = count($query2)-1;
        //$created = $query2[$ind];
            
        $titles = '';
        foreach ($result as $row) {
          $titles .= $row->title.'<br />';
        }

        //$lists = '<p>Database last updated: '. $created .'</br>';
        $lists = '';
        $lists .= 'Number of documents: '. $num .'<br/>';
        $lists .= '</p>';

        $lists .= 'Legislation beginning with:</p>';        
        $word = '<p></p>';
        foreach(range('A','Z') as $i) {
           //$word .= (array_key_exists ("$i", $alpha)) ? "<a href='consol_legbegin?letter=$i&legisname=$legtype'".">".$i."</a>" : "$i";
        $word .= (array_key_exists ("$i", $alpha)) ? t('<a href="@url">'.$i.'</a>', array('@url' => url('consol_leglist/'.$legtype.'/'.strtolower($i)))) : "$i";
        $word .= ($i != 'Z') ? ' | ':'';
        }

        $years_cont = '';
        $years_range = '';
        if($consoldate_num > 0){ //checking if consolidated dates exist
          $years_cont = '<p></p><p>Legislation for the years:</p>';
          sort($date_year);
          $years_range = '<p></p>';
          foreach($date_year as $year) {
              //$years_range .= "<a href='consol_leglistyear?legname=$legname&year=$year'>| $year </a> ";
            $years_range .= t('<a href="@url">'.$year.'</a> | ', array('@url' => url('consol_leglist/'.$legtype.'/'.$year)));
          }
        }
        

        $content['content'] = array(
          '#markup'=>t($lists.$word.$years_cont.$years_range),
        );
    }
    else{
      $content['content'] = array(
      '#markup'=>t("<strong>There are currently no legislations loaded</strong>"),
      );
    }
    
  }
  //Checking Legislation promulgated
  else if($legtype == "legislation_promulgated"){
    $legname = str_replace('-',' ',$legname);
    $legname = str_replace('_',' ',$legname);
    $legname = ucwords($legname);
    
    drupal_set_title($legname);
    
    $result = db_query("SELECT * FROM {node} WHERE type = '$legtype' ");

    $result2 = db_query("SELECT p.field_commencedate_value FROM {field_data_field_commencedate} p 
     WHERE p.bundle ='$legtype' ");  


    $date_ar = array();
    $date_year = array();
    foreach($result2 as $dt){

      $date_ar[] = date('j F Y',strtotime($dt->field_commencedate_value)).'<br/>';
      $yearval = date('Y',strtotime($dt->field_commencedate_value));
      
      if(!in_array($yearval,$date_year))
        $date_year[] = $yearval;
    }
    $num = $result->rowCount();

    $promdate_count = $result2->rowCount();

    //echo $num;exit;
    //query to extract the first letter of the judgment
    if($promdate_count > 0){
       $sqlresult = db_query("SELECT SUBSTRING(nd.title,1,1) AS letter,nd.title, cdate.field_commencedate_value FROM {node} nd INNER JOIN {field_data_field_commencedate} cdate ON 
    nd.nid = cdate.entity_id WHERE cdate.bundle = '$legtype' ORDER BY nd.title ");
    }
    else{
      $sqlresult = db_query("SELECT SUBSTRING(nd.title,1,1) AS letter,nd.title FROM {node} nd  WHERE nd.type = '$legtype' ORDER BY nd.title ");
    }
   
    //print_r($sqlresult);
    $alpha = array();
    foreach($sqlresult as $letters){
      $alpha[$letters->letter] = $letters->title;
    }

    if($num > 0){
   
        $titles = '';
        foreach ($result as $row) {
          $titles .= $row->title.'<br />';
        }

        //$content['titles'] = $titles;
        $lists = '';
        //$lists = '<p>Database last updated: '. $created .'';
        $lists .= 'Number of documents: '. $num .'<br/>';
        $lists .= '</p>';
        $lists .= 'Legislation beginning with:</p>';

        
        $word = '<p></p>';
        foreach(range('A','Z') as $i) {
          //$word .= (array_key_exists ("$i", $alpha)) ? "<a href='consol_legbegin?letter=$i&legisname=$legtype'".">".$i."</a>" : "$i";
          //$word .= ($i != 'Z') ? ' | ':'';    
          //$word .= (array_key_exists ("$i", $alpha)) ? t('<a href="@url">'.$i.'</a>', array('@url' => url('consol_legbegin/'.$legtype.'/'.strtolower($i)))) : "$i";
          $word .= (array_key_exists ("$i", $alpha)) ? t('<a href="@url">'.$i.'</a>', array('@url' => url('consol_leglist/'.$legtype.'/'.strtolower($i)))) : "$i";
          $word .= ($i != 'Z') ? ' | ':'';
        }

        $years_cont = '';
        $years_range = '';
        if($promdate_count > 0){
          $years_cont = '<p></p><p>Legislation for the years:</p>';
          sort($date_year);
          $years_range = '<p></p>';
          foreach($date_year as $year) {
            //$years_range .= "<a href='consol_leglistyear?legname=$legname&year=$year'>| $year </a> ";
            $years_range .= t('<a href="@url">'.$year.'</a> | ', array('@url' => url('consol_leglist/'.$legtype.'/'.$year)));

          }
        }
        $content['content'] = array(
          '#markup'=>t($lists.$word.$years_cont.$years_range),
        );
    }
    else{
      $content['content'] = array(
      '#markup'=>t("<strong>There are currently no legislations loaded</strong>"),
      );
    }
   
  }
  //Checking Legislation promulgated
  else if($legtype == "subordinate_legislation"){
    $legname = str_replace('-',' ',$legname);
    $legname = ucwords($legname);
    
    drupal_set_title($legname);
    
    $result = db_query("SELECT * FROM {node} WHERE type = '$legtype' ");

    $result2 = db_query("SELECT pdate.field_subpromdate_value FROM {field_data_field_subpromdate} pdate
    WHERE pdate.bundle ='$legtype' ");  


    $date_ar = array();
    $date_year = array();
    foreach($result2 as $dt){

      $date_ar[] = date('j F Y',strtotime($dt->field_subpromdate_value)).'<br/>';
      $yearval = date('Y',strtotime($dt->field_subpromdate_value));
      if(!in_array($yearval,$date_year))
        $date_year[] = $yearval;
    }
    $num = $result->rowCount();

    //print_r($date_year);
    //echo $num;exit;
    //query to extract the first letter of the judgment
    $sqlresult = db_query("SELECT SUBSTRING(nd.title,1,1) AS letter,nd.title, pdate.field_subpromdate_value FROM {node} nd INNER JOIN {field_data_field_subpromdate} pdate ON 
    nd.nid = pdate.entity_id WHERE pdate.bundle = '$legtype' ORDER BY nd.title ");
    
    $alpha = array();

    foreach($sqlresult as $letters){
      $alpha[$letters->letter] = $letters->title;
    }


    if($num > 0){
        //echo "TEST";exit;   
        //$created = min($date_ar);
            
        $titles = '';
        foreach ($result as $row) {
          $titles .= $row->title.'<br />';
        }

        //$content['titles'] = $titles;
        $lists = '';
        //$lists = '<p>Database last updated: '. $created .'';
        $lists .= 'Number of documents: '. $num .'<br/>';
        $lists .= '</p>';
        $lists .= 'Legislation beginning with:</p>';

        
        $word = '<p></p>';
        foreach(range('A','Z') as $i) {
          //$word .= (array_key_exists ("$i", $alpha)) ? "<a href='consol_legbegin?letter=$i&legisname=$legtype'".">".$i."</a>" : "$i";
          $word .= (array_key_exists ("$i", $alpha)) ? t('<a href="@url">'.$i.'</a>', array('@url' => url('consol_leglist/'.$legtype.'/'.strtolower($i)))) : "$i";
          $word .= ($i != 'Z') ? ' | ':'';    
        }

        $years_cont = '<p></p><p>Legislation for the years:</p>';
        sort($date_year);
        $years_range = '<p></p>';
        foreach($date_year as $year) {
          //$years_range .= "<a href='consol_leglistyear?legname=$legname&year=$year'>| $year </a> ";
          $years_range .= t('<a href="@url">'.$year.'</a> | ', array('@url' => url('consol_leglist/'.$legtype.'/'. $year)));
        }

        $content['content'] = array(
          '#markup'=>t($lists.$word.$years_cont.$years_range),
        );
    }
    else{
      $content['content'] = array(
      '#markup'=>t("<strong>There are currently no legislations loaded</strong>"),
      );
    }
  }
  //Checking Legislation promulgated
  else if($legtype == "gazette_legislation"){
    $legname = str_replace('-',' ',$legname);
    $legname = ucwords($legname);
    
    drupal_set_title($legname);
    
    $result = db_query("SELECT * FROM {node} WHERE type = '$legtype' ");

    $result2 = db_query("SELECT pdate.field_gaz_publication_date_value FROM {field_data_field_gaz_publication_date} pdate
    WHERE pdate.bundle ='$legtype' ");  


    $date_ar = array();
    $date_year = array();
    foreach($result2 as $dt){

      $date_ar[] = date('j F Y',strtotime($dt->field_gaz_publication_date_value)).'<br/>';
      $yearval = date('Y',strtotime($dt->field_gaz_publication_date_value));
      if(!in_array($yearval,$date_year))
        $date_year[] = $yearval;
    }
    $num = $result->rowCount();

    //print_r($date_year);
    //echo $num;exit;
    //query to extract the first letter of the judgment
    $sqlresult = db_query("SELECT SUBSTRING(nd.title,1,1) AS letter,nd.title, pdate.field_gaz_publication_date_value FROM {node} nd INNER JOIN {field_data_field_gaz_publication_date} pdate ON 
    nd.nid = pdate.entity_id WHERE pdate.bundle = '$legtype' ORDER BY nd.title ");
    
    $alpha = array();

    foreach($sqlresult as $letters){
      $alpha[$letters->letter] = $letters->title;
    }


    if($num > 0){
        //echo "TEST";exit;   
        //$created = min($date_ar);
            
        $titles = '';
        foreach ($result as $row) {
          $titles .= $row->title.'<br />';
        }

        //$content['titles'] = $titles;
        $lists = '';
        //$lists = '<p>Database last updated: '. $created .'';
        $lists .= 'Number of documents: '. $num .'<br/>';
        $lists .= '</p>';
        $lists .= 'Legislation beginning with:</p>';

        
        $word = '<p></p>';
        foreach(range('A','Z') as $i) {
          //$word .= (array_key_exists ("$i", $alpha)) ? "<a href='consol_legbegin?letter=$i&legisname=$legtype'".">".$i."</a>" : "$i";
          $word .= (array_key_exists ("$i", $alpha)) ? t('<a href="@url">'.$i.'</a>', array('@url' => url('consol_leglist/'.$legtype.'/'.strtolower($i)))) : "$i";
          $word .= ($i != 'Z') ? ' | ':'';    
        }

        $years_cont = '<p></p><p>Legislation for the years:</p>';
        sort($date_year);
        $years_range = '<p></p>';
        foreach($date_year as $year) {
          //$years_range .= "<a href='consol_leglistyear?legname=$legname&year=$year'>| $year </a> ";
          $years_range .= t('<a href="@url">'.$year.'</a> | ', array('@url' => url('consol_leglist/'.$legtype.'/'. $year)));
        }

        $content['content'] = array(
          '#markup'=>t($lists.$word.$years_cont.$years_range),
        );
    }
    else{
      $content['content'] = array(
        '#markup'=>t("<strong>There are currently no legislations loaded</strong>"),
      );
    }
  }
  else if($legtype == "bills_legislation"){
    $legname = str_replace('-',' ',$legname);
    $legname = ucwords($legname);
    
    drupal_set_title($legname);
    
    $result = db_query("SELECT * FROM {node} WHERE type = '$legtype' ");

    $result2 = db_query("SELECT pdate.field_date_introduced_value FROM {field_data_field_date_introduced} pdate
    WHERE pdate.bundle ='$legtype' ");  


    $date_ar = array();
    $date_year = array();
    foreach($result2 as $dt){

      $date_ar[] = date('j F Y',strtotime($dt->field_date_introduced_value)).'<br/>';
      $yearval = date('Y',strtotime($dt->field_date_introduced_value));
      if(!in_array($yearval,$date_year))
        $date_year[] = $yearval;
    }
    $num = $result->rowCount();

    //print_r($date_year);
    //echo $num;exit;
    //query to extract the first letter of the judgment
    $sqlresult = db_query("SELECT SUBSTRING(nd.title,1,1) AS letter,nd.title, pdate.field_date_introduced_value FROM {node} nd INNER JOIN {field_data_field_date_introduced} pdate ON 
    nd.nid = pdate.entity_id WHERE pdate.bundle = '$legtype' ORDER BY nd.title ");
    
    $alpha = array();

    foreach($sqlresult as $letters){
      $alpha[$letters->letter] = $letters->title;
    }


    if($num > 0){
        //echo "TEST";exit;   
        //$created = min($date_ar);
            
        $titles = '';
        foreach ($result as $row) {
          $titles .= $row->title.'<br />';
        }

        //$content['titles'] = $titles;
        $lists = '';
        //$lists = '<p>Database last updated: '. $created .'';
        $lists .= 'Number of documents: '. $num .'<br/>';
        $lists .= '</p>';
        $lists .= 'Legislation beginning with:</p>';

        
        $word = '<p></p>';
        foreach(range('A','Z') as $i) {
          //$word .= (array_key_exists ("$i", $alpha)) ? "<a href='consol_legbegin?letter=$i&legisname=$legtype'".">".$i."</a>" : "$i";
          $word .= (array_key_exists ("$i", $alpha)) ? t('<a href="@url">'.$i.'</a>', array('@url' => url('consol_leglist/'.$legtype.'/'.strtolower($i)))) : "$i";
          $word .= ($i != 'Z') ? ' | ':'';    
        }

        $years_cont = '<p></p><p>Legislation for the years:</p>';
        sort($date_year);
        $years_range = '<p></p>';
        foreach($date_year as $year) {
          //$years_range .= "<a href='consol_leglistyear?legname=$legname&year=$year'>| $year </a> ";
          $years_range .= t('<a href="@url">'.$year.'</a> | ', array('@url' => url('consol_leglist/'.$legtype.'/'. $year)));
        }

        $content['content'] = array(
          '#type' => 'fieldset',
          //'#description'=>t($lists.$word),
          '#description'=>t($lists.$word.$years_cont.$years_range),
        );
    }
    else{
      $content['content'] = array(
        '#markup'=>t("<strong>There are currently no legislations loaded</strong>"),
      );
    }
  }
  return $content;
}


function legislation_beginwith($current_path){

    //Code added for fixing the url-path
    $path_ar = explode('/',current_path());
    $legtype = $path_ar[1];
    $letter = strtoupper($path_ar[2]);

    if(strlen($letter) == 1){

        $legisname = db_query("SELECT name FROM {node_type} WHERE type = '$legtype' ")->fetchField();
        //$courtname = str_replace('-',' ',$passedcourtname);
        //$courtname = ucwords($courtname);
        drupal_set_title($legisname .' beginning with '.$letter);

        $queryres=db_query("SELECT nd.title, ualias.alias
        FROM {node} nd INNER JOIN {url_alias} ualias ON
        ualias.source = CONCAT('node/',nd.nid) 
        AND nd.title LIKE '$letter%'
        AND nd.type = '$legtype' ");


        $data = '<p><strong>type:</strong> judgment';
        $data .= '<p><strong>database:</strong> '.$legisname;
        $data .= '<p><strong>alpha:</strong> '.$letter;
        $data .= "<p><ul>";
        foreach($queryres as $result){
          $content_title = $result->title;
          $content_src = $result->alias;
          //$data .="<li><a href='$content_src'>$content_title</a></li>"; 
          $data .= t('<li><a href="@url">'.$content_title.'</a></li>', array('@url' => url($content_src)));
        }
        $data .= "</ul></p>";

        $content['content'] = array(
          '#markup'=>t($data),
        );
        return $content;
    }
    else if(strlen($letter) == 4){

        $path_ar = explode('/',$current_path);
       // print_r($path_ar);
        $legtype = $path_ar[1];
        $year = $path_ar[2];
        
        
        //$metadata = '<p><strong>type:</strong>Legislation';
        $metadata = '';
        //$metadata .= '<p><strong>database:</strong>'.$legtype;
        //$metadata .= '<p><strong>year:</strong>'.$year;

        $legname = db_query("SELECT name FROM {node_type} WHERE type = '$legtype' ")->fetchField();
        drupal_set_title($legname.' commenced year '.$year);

        if($legtype == "legislation_promulgated"){      

          
          $result = db_query("SELECT n.title,DATE_FORMAT(pdate.field_commencedate_value,'%Y'),ualias.alias FROM {node} n     
            INNER JOIN {field_data_field_commencedate} pdate
            ON n.nid = pdate.entity_id
            AND DATE_FORMAT(pdate.field_commencedate_value,'%Y') = '$year'
            INNER JOIN {url_alias} ualias
            ON CONCAT('node/',n.nid) = ualias.source
            ORDER BY n.title ");

          $date_month = array();
          

          $date_ar = array();  
          $titles = '<p><ul>';  
          $prev_month = "";
         
          foreach($result as $res){        
            $alias = $res->alias;
            $titles .= t('<li><a href="@url">'.$res->title.'</a></li>', array('@url' => url($alias)));       
          }// End of for loop
          
          $titles .= '</ul></p>';
          
          $content['content'] = array(
            '#markup'=>t($metadata.$titles),
          );
        }
        else if($legtype == "consolidated_legislation"){      
          
          $result = db_query("SELECT n.title,cdate.field_consoldate_value,ualias.alias FROM {node} n     
            INNER JOIN {field_data_field_consoldate} cdate
            ON cdate.entity_id = n.nid 
            INNER JOIN {url_alias} ualias
            ON CONCAT('node/',n.nid) = ualias.source
            ORDER BY n.title ");

          $date_month = array();
          

          $date_ar = array();  
          $months = '<p></p>';
          $titles = '<p><ul>';  
          $prev_month = "";
         
          foreach($result as $res){        
            $alias = $res->alias;
            if(date('Y',strtotime($res->field_consoldate_value)) == $year){
              $titles .= '<li>'."<a href='/$alias'>".$res->title.'</a></li>'; 
            }
                   
          }// End of for loop
          
          $titles .= '</ul></p>';
          
          $content['content'] = array(
            '#markup'=>t($metadata.$months.$titles),
          );
        }

        else if( $legtype == "subordinate_legislation"){        
          $result = db_query("SELECT n.title,DATE_FORMAT(subyear.field_subpromdate_value,'%Y'),ualias.alias FROM {node} n     
            INNER JOIN {field_data_field_subpromdate} subyear
            ON subyear.entity_id = n.nid 
            AND DATE_FORMAT(subyear.field_subpromdate_value,'%Y') = '$year'
            INNER JOIN {url_alias} ualias
            ON CONCAT('node/',n.nid) = ualias.source
            ORDER BY n.title ");

          $date_month = array();
          

          $date_ar = array();  
          $months = '<p></p>';
          $titles = '<p><ul>';  
          $prev_month = "";
         
          foreach($result as $res){        
            $alias = $res->alias;
              $titles .= '<li>'."<a href='/$alias'>".$res->title.'</a></li>';        
          }// End of for loop
          
          $titles .= '</ul></p>';
          
          $content['content'] = array(
            '#markup'=>t($metadata.$months.$titles),
          );
        }
        else if( $legtype == "gazette_legislation"){        
          $result = db_query("SELECT n.title,DATE_FORMAT(subyear.field_gaz_publication_date_value,'%Y'),ualias.alias FROM {node} n     
            INNER JOIN {field_data_field_gaz_publication_date} subyear
            ON subyear.entity_id = n.nid 
            AND DATE_FORMAT(subyear.field_gaz_publication_date_value,'%Y') = '$year'
            INNER JOIN {url_alias} ualias
            ON CONCAT('node/',n.nid) = ualias.source
            ORDER BY n.title ");

          $date_month = array();
          

          $date_ar = array();  
          $months = '<p></p>';
          $titles = '<p><ul>';  
          $prev_month = "";
         
          foreach($result as $res){        
            $alias = $res->alias;
              $titles .= '<li>'."<a href='/$alias'>".$res->title.'</a></li>';        
          }// End of for loop
          
          $titles .= '</ul></p>';
          
          $content['content'] = array(
            '#markup'=>t($metadata.$months.$titles),
          );
        }
        else if( $legtype == "bills_legislation"){        
          $result = db_query("SELECT n.title,DATE_FORMAT(subyear.field_date_introduced_value,'%Y'),ualias.alias FROM {node} n     
            INNER JOIN {field_data_field_date_introduced} subyear
            ON subyear.entity_id = n.nid 
            AND DATE_FORMAT(subyear.field_date_introduced_value,'%Y') = '$year'
            INNER JOIN {url_alias} ualias
            ON CONCAT('node/',n.nid) = ualias.source
            ORDER BY n.title ");

          $date_month = array();
          

          $date_ar = array();  
          $months = '<p></p>';
          $titles = '<p><ul>';  
          $prev_month = "";
         
          foreach($result as $res){        
            $alias = $res->alias;
              $titles .= '<li>'."<a href='/$alias'>".$res->title.'</a></li>';        
          }// End of for loop
          
          $titles .= '</ul></p>';
          
          $content['content'] = array(
            '#markup'=>t($metadata.$months.$titles),
          );
        }
        return $content;
    }

}
