<?php

 // require_once('../access_check.inc');
/**
 * Implements hook_menu()
 * @return array
 */
function journalarticlealphalisting_menu() {
 
  $aItems = array(
      'journalarticlealphalisting' => array(
        'title' => 'Articles',
        'page callback' => '_page_journalarticlealphalisting',
        //'access callback' => TRUE,
        'access arguments' => array('access journalarticlealphalisting'),
        'type' => MENU_NORMAL_ITEM,
      ),
    );
  return $aItems;
}
 
/**
 * Page callback mapped to the url /hello_world
 *
 * @return array
 */
function _page_journalarticlealphalisting() {
        //return array(
          //'#markup' => '<p>Hello world</p>'
        //);

        $content = array();
        $journalname = '';
        if(isset($_GET['journalname']))
          $journalname = $_GET['journalname'];
        $type = 'journal';
     
        drupal_set_title($journalname);
        
        $result = db_query("SELECT n.title FROM {node} n WHERE n.type = '$type' ");

        $result2 = db_query("SELECT pubdate.field_jpubdate_value,jtitle.field_journaltitle_select_value FROM {field_data_field_jpubdate} pubdate 
          INNER JOIN {field_data_field_journaltitle_select} jtitle
          ON pubdate.entity_id = jtitle.entity_id
          AND jtitle.field_journaltitle_select_value = '$journalname'
          AND pubdate.bundle ='$type' ");  

        //print_r($result);exit;
        $date_ar = array();
        $date_year = array();
        foreach($result2 as $dt){

          $date_ar[] = date('j F Y',strtotime($dt->field_jpubdate_value)).'<br/>';

          $year_val = date('Y',strtotime($dt->field_jpubdate_value));
          if(!in_array($year_val,$date_year))
            $date_year[] = $year_val;
        }
        $num = $result2->rowCount();

        //echo $num;exit;
        //query to extract the first letter of the judgment
        $sqlresult = db_query("SELECT SUBSTRING(nd.title,1,1) AS letter,nd.title, cdate.field_jpubdate_value FROM {node} nd INNER JOIN {field_data_field_jpubdate} cdate ON 
        nd.nid = cdate.entity_id WHERE cdate.bundle = '$type' ORDER BY nd.title ");
        
        $alpha = array();

        foreach($sqlresult as $letters){
          $alpha[$letters->letter] = $letters->title;
        }


        if($num > 0){
            //echo "TEST";exit;   
            $created = min($date_ar);
                
            $titles = '';
            foreach ($result as $row) {
              $titles .= $row->title.'<br />';
            }

            //$content['titles'] = $titles;
            $lists = '<p>Database last updated: '. $created .'';
            $lists .= 'Number of documents: '. $num .'<br/>';
            $lists .= '</p>';
            $lists .= 'Legislation beginning with:</p>';

            
            $word = '<p></p>';
            foreach(range('A','Z') as $i) {
              $word .= (array_key_exists ("$i", $alpha)) ? "<a href='journalarticlebeginwith?letter=$i&journalname=$journalname'".">".$i."</a>" : "$i";
              $word .= ($i != 'Z') ? ' | ':'';    
            }

            $years_cont = '<p></p><p>Legislation for the years:</p>';
            sort($date_year);
            $years_range = '<p></p>';
            foreach($date_year as $year) {
                $years_range .= "<a href='journalarticleyearlisting?journalname=$journalname&year=$year'>| $year </a> ";
            }

            $content['content'] = array(
              '#type' => 'fieldset',
              //'#description'=>t($lists.$word),
              '#description'=>t($lists.$word.$years_cont.$years_range),
            );
        }
        else{
          $content['content'] = array(
          '#type' => 'fieldset',
          '#description'=>t("<strong>There are currently no articles loaded for this Journal</strong>"),
          );
        }

        return $content;  
}


function _checkAccess(){
  global $user;
  if ($user->uid) { // user is logged in
    return TRUE;
  } // Anonymous
  return FALSE;
}
