<?php

 // require_once('../access_check.inc');
/**
 * Implements hook_menu()
 * @return array
 */
function journalarticle_menu() {
 
  $aItems = array(
      'journalarticle' => array(
        'title' => 'Journal Articles',
        'page callback' => '_page_journalarticle_output',
        'access callback' => TRUE,
        'access arguments' => array('access journalarticle'),
        'type' => MENU_NORMAL_ITEM,
      ),
    );
  return $aItems;
}
 


function _page_journalarticle_output() {

      $content = array();
      $path = current_path();
      $path_ar = explode('/',$path);

      //exit;
      //if()
      //echo count($path_ar);exit;
      if(count($path_ar) == 1){
        return array(
          '#markup'=>t('Select a Journal'),
        );   
      }
      if(count($path_ar) == 2){
        return _page_journalarticle($path);
      }
     elseif (count($path_ar) == 3){
       return _page_journalarticlebegwith($path);
     }
      


}


/**
 * Page callback mapped to the url /_page_journalarticle
 *
 * @return array
 */
function _page_journalarticle($current_path) {
        
        /*$content = array();
        $journalname = '';
        if(isset($_GET['journalname']))
          $journalname = $_GET['journalname']; */
        $type = 'journal';

//print_r($current_path);exit;
        $path_ar = explode('/',$current_path);
        //print_r($path_ar);
        $passedjournalname = $path_ar[1];
        //$letter = strtoupper($path_ar[2]);
        $journalname = str_replace('-',' ',$passedjournalname);
        $journalname = ucwords($journalname);
     
        drupal_set_title($journalname);
        
        $result = db_query("SELECT n.title FROM {node} n WHERE n.type = '$type' ");

        $result2 = db_query("SELECT pubdate.field_jnpubdate_value,jtitle.field_journaltitle_select_value FROM {field_data_field_jnpubdate} pubdate 
          INNER JOIN {field_data_field_journaltitle_select} jtitle
          ON pubdate.entity_id = jtitle.entity_id
          AND jtitle.field_journaltitle_select_value = '$journalname'
          AND pubdate.bundle ='$type' ");  

        if($result2->rowCount() > 0){

          //print_r($result);exit;
          $date_ar = array();
          $date_year = array();
          foreach($result2 as $dt){

            $date_ar[] = date('j F Y',strtotime($dt->field_jnpubdate_value)).'<br/>';

            $year_val = date('Y',strtotime($dt->field_jnpubdate_value));
            if(!in_array($year_val,$date_year))
              $date_year[] = $year_val;
          }
          $num = $result2->rowCount();

          //echo $num;exit;
          //query to extract the first letter of the judgment
          $sqlresult = db_query("SELECT SUBSTRING(nd.title,1,1) AS letter,nd.title, cdate.field_jnpubdate_value FROM {node} nd INNER JOIN {field_data_field_jnpubdate} cdate ON 
          nd.nid = cdate.entity_id WHERE cdate.bundle = '$type' ORDER BY nd.title ");
          
          $alpha = array();

          foreach($sqlresult as $letters){
            $alpha[$letters->letter] = $letters->title;
          }


          //if($num > 0){
              //echo "TEST";exit;   
              $created = min($date_ar);
                  
              $titles = '';
              foreach ($result as $row) {
                $titles .= $row->title.'<br />';
              }

              //$content['titles'] = $titles;
              //$lists = '<p>Database last updated: '. $created .'';
              $lists = 'Number of documents: '. $num .'<br/>';
              $lists .= '</p>';
              $lists .= 'Articles beginning with:</p>';

              
              $word = '<p></p>';
              foreach(range('A','Z') as $i) {
                //$word .= (array_key_exists ("$i", $alpha)) ? "<a href='/journalarticle/$passedjournalname/$i'".">".$i."</a>" : "$i";
                $word .= (array_key_exists ("$i", $alpha)) ? t('<a href="@url">'.$i.'</a>', array('@url' => url('journalarticle/'.$passedjournalname.'/'.strtolower($i)))) : "$i";
                $word .= ($i != 'Z') ? ' | ':'';    
              }

              $years_cont = '<p></p><p>Articles for the years:</p>';
              sort($date_year);
              $years_range = '<p></p>';
              foreach($date_year as $year) {
                  //$years_range .= "<a href='/journalarticle/$passedjournalname/$year'>| $year </a> ";
                 $years_range .= t('<a href="@url">'.$year.'</a>|', array('@url' => url('journalarticle/'.$passedjournalname.'/'.$year)));
              }

              $content['content'] = array(
                
                //'#description'=>t($lists.$word),
                '#markup'=>t($lists.$word.$years_cont.$years_range),
              );
          //}
          
        }
        else{
            $content['content'] = array(
            
            '#markup'=>t("<strong>There are currently no articles loaded for this Journal</strong>"),
            );
          }

        return $content;  
}


function _page_journalarticlebegwith($current_path) {
   
        $content = array();
        $journalname = '';
        /*if(isset($_GET['journalname']))
          $journalname = $_GET['journalname']; */
        $type = 'journal';

        $path_ar = explode('/',$current_path);
        //print_r($path_ar);
        $passedjournalname = $path_ar[1];
        //echo $passedjournalname;
        $letter = strtoupper($path_ar[2]);
        $journalname = str_replace('-',' ',$passedjournalname);
        $journalname = ucwords($journalname);
        
        /*$courtname = '';
        if(isset($_GET['letter']) && isset($_GET['journalname'])){
          $letter = $_GET['letter'];
           $jname = $_GET['journalname'];
        }*/
        

       if(strlen($letter) == 1){
            drupal_set_title('Journal Articles beginning with'.' '.$letter);

          $queryres=db_query("SELECT nd.title, ualias.alias, jtitle.field_journaltitle_select_value 
          FROM {node} nd INNER JOIN {field_data_field_journaltitle_select} jtitle ON 
          nd.nid = jtitle.entity_id
          INNER JOIN {url_alias} ualias ON
          ualias.source = CONCAT('node/',nd.nid) 
          AND nd.title LIKE '$letter%'
          AND jtitle.field_journaltitle_select_value LIKE '%$journalname%'
          AND nd.type = 'journal' ");


          $data = '<p><strong>type:</strong> journal';
          $data .= '<p><strong>database:</strong> Journal Articles';
          $data .= '<p><strong>alpha:</strong> '.$letter;
          $data .= "<p><ul>";
          foreach($queryres as $result){
            $content_title = $result->title;
            $content_src = $result->alias;
            //$data .="<li><a href='$content_src'>$content_title</a></li>"; 
            $data .= t('<li><a href="@url">'.$content_title.'</a></li>', array('@url' => url($content_src)));
          }
          $data .= "</ul></p>";

          $content['content'] = array(
            '#markup'=>t($data),
          );
        }
        else{
            
            $type = 'journal';

            $path_ar = explode('/',$current_path);
            //print_r($path_ar);
            $passedjournalname = $path_ar[1];
            //echo $passedjournalname;
            $year = strtoupper($path_ar[2]);
            $journalname = str_replace('-',' ',$passedjournalname);
            $journalname = ucwords($journalname);
            drupal_set_title($year.' '.$journalname);
     
            $metadata = '<p><strong>type:</strong>Journals';
            $metadata .= '<p><strong>database:</strong>'.$journalname;
            $metadata .= '<p><strong>year:</strong>'.$year;

            $result = db_query("SELECT pdate.field_jnpubdate_value,n.title,ualias.alias FROM {field_data_field_jnpubdate} pdate     
              INNER JOIN {field_data_field_journaltitle_select} jtitle
              ON jtitle.entity_id = pdate.entity_id 
              INNER JOIN {node} n 
              ON n.nid = pdate.entity_id
              AND n.type = 'journal'
              INNER JOIN {url_alias} ualias
              ON CONCAT('node/',n.nid) = ualias.source
              WHERE jtitle.field_journaltitle_select_value LIKE '%$journalname%' ORDER BY pdate.field_jnpubdate_value, n.title ");

            $date_month = array();
            
            //echo $result->title;

            $date_ar = array();  
            $months = '<p></p>';
            $titles = '<p><ul>';  
            $prev_month = "";
           
            foreach($result as $res){
              $yearjudg = date('Y',strtotime($res->field_jnpubdate_value));    
              $content_month = date('F Y',strtotime($res->field_jnpubdate_value));
              $monthjudg = date('F',strtotime($res->field_jnpubdate_value));  
              $alias = $res->alias;

              if($yearjudg == $year){   
                     
                //$titles .= '<li>'."<a href='$alias'>".$res->title.'</a></li>';
                $titles .= t('<li><a href="@url">'.$res->title.'</a></li>', array('@url' => url($res->alias)));
                $prev_month = $content_month;
              }            
            }// End of for loop
            
            $titles .= '</ul></p>';
            
            $content['content'] = array(
              '#markup'=>t($metadata.$months.$titles),
            );
        }  
        return $content; 
     
}

