<?php
/**
 * Implements hook_menu()
 * @return array
 */
function helloworld_menu() {
 
  $aItems = array(
      'hello_world' => array(
        'title' => 'Hello world',
        'page callback' => '_page_hello_world',
        'access callback' => TRUE,
      ),
    );
  return $aItems;
}
 
/**
 * Page callback mapped to the url /hello_world
 *
 * @return array
 */
function _page_hello_world() {
  return array(
    '#markup' => '<p>Hello world</p>'
  );
}

