<?php

/**
 * @file
 */

function indigo_menu() {
	// Indigo admin.
	$items['admin/config/services/indigo'] = array(
		'title' => t('Indigo API'),
		'description' => t('Integration with the Indigo API to pull content into Drupal.'),
	    'page callback' => 'drupal_get_form',
	    'page arguments' => array('indigo_admin'),
	    'access arguments' => array('administer indigo settings'),
	    'type' => MENU_NORMAL_ITEM,
	);

	$items['admin/config/services/indigo/test'] = array(
		'title' => t('Test Indigo API'),
	    'page callback' => '__test_indigo_fetch',
	    'access arguments' => array('administer indigo settings'),
	    'type' => MENU_CALLBACK,
	);

	return $items;
}

function indigo_admin() {
	$form = array();

	$form['indigo_api_url'] = array(
		'#type' => 'textfield',
		'#title' => t('Indigo API URL'),
		'#default_value' => variable_get('indigo_api_url', 'https://indigo.code4sa.org/api'),
		'#description' => t("The maximum number of links to display in the block."),
		'#required' => TRUE,
	);

	$form['indigo_site_country_code'] = array(
		'#type' => 'select',
		'#title' => t('Import for Country'),
		'#default_value' => variable_get('indigo_site_country_code', '<all>'),
		'#options' => __country_codes(),
		'#description' => t("Set which country documents should be imported for this site."),
		'#required' => TRUE,
	);

	return system_settings_form($form);
}

function indigo_sync_content($data = array()) {
	drupal_set_message('<pre>'. print_r($data, true) .'<pre>');

	foreach ($data as $d) {
		$query = new EntityFieldQuery();
		$entities = $query->entityCondition('entity_type', 'node')
			->propertyCondition('type', variable_get('indigo_document_content_type', 'indigo_document'))
			->propertyCondition('title', $d['title'])
			->range(0,1)
			->execute();

		if (!empty($entities['node'])) {
			continue;
		}

		// entity_create replaces the procedural steps in the first example of
		// creating a new object $node and setting its 'type' and uid property
		$values = array(
		  'type' => variable_get('indigo_document_content_type', 'indigo_document'),
		  'uid' => 1,
		  //'status' => true,
		  //'comment' => false,
		  //'promote' => false,
		);
		$entity = entity_create('node', $values);

		// The entity is now created, but we have not yet simplified use of it.
		// Now create an entity_metadata_wrapper around the new node entity
		// to make getting and setting values easier
		$ewrapper = entity_metadata_wrapper('node', $entity);

		// Using the wrapper, we do not have to worry about telling Drupal
		// what language we are using. The Entity API handles that for us.
		$ewrapper->title->set($d['title']);

		foreach ($d['fields'] as $fk => $fv) {
			$ewrapper->{$fk}->set($fv);
		}

		// Setting the body is a bit different from other properties or fields
		// because the body can have both its complete value and its
		// summary
		//if (isset($node['body']['und'])) {
		//	$ewrapper->body->set(array('value' => $node['body']['und'][0]['value'], 'format' => $node['body']['und'][0]['format']));
		//	$ewrapper->body->summary->set($node['body']['und'][0]['summary']);
		//}

		// Now just save the wrapper and the entity
		// There is some suggestion that the 'true' argument is necessary to
		// the entity save method to circumvent a bug in Entity API. If there is
		// such a bug, it almost certainly will get fixed, so make sure to check.
		$ewrapper->save();

		// Update the created and changed date on the new node to 
		// what they should be.
		/*
		db_update('node')
			->fields(array(
				'created' => $node['created'],
				'changed' => $node['changed'],
			))
			->condition('nid', $ewrapper->getIdentifier(), '=')
  			->execute();
  		*/
	}
}

function __test_indigo_fetch() {
	$output = '';

	drupal_set_message('API:<pre>'. print_r(variable_get('indigo_api_url', ''), true) .'</pre>');
	drupal_set_message('Country Code:<pre>'. print_r(variable_get('indigo_site_country_code', '<all>'), true) .'</pre>');
	
	$indigo_data = __fetch_indigo_content('', array());

	drupal_set_message('<pre>'. print_r($indigo_data->results, true) .'</pre>');

	$data = array();
	foreach ($indigo_data->results as $id) {
		$output .= '<h3>'. $id->title .'</h3>';
		$output .= '<p>'. $id->frbr_uri .'</p>';
		$output .= '<p>&nbsp;</p>';

		$data[] = array(
			'title' => $id->title,
			'fields' => array(
				'field_doc_country' => strtoupper($id->country),
				'field_doc_locality' => $id->locality,
				'field_doc_language' => $id->language,
				'field_doc_subtype' => $id->subtype,
				'field_doc_frbr' => $id->frbr_uri,
			),
		);
	}
	indigo_sync_content($data);

	return $output;
}

function __fetch_indigo_content($endpoint = '', $payload = array()) {
	$api_url = variable_get('indigo_api_url', '');
	$api_country_code = strtolower(variable_get('indigo_site_country_code', '<all>'));
	if ($api_country_code != '<all>') {
		$api_url .=  '/'. $api_country_code;
	}

	$url = $api_url .'/'. $endpoint;

	$ch = curl_init();

	curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
	curl_setopt($ch, CURLOPT_URL,$url);

	$result = json_decode(curl_exec($ch));
	curl_close($ch);

	return $result;
}

function __country_codes_lookup($code = null, $name = null) {
	$countries = __country_codes();

	if (!empty($code)) {
		$code = strtoupper($code);

		return $countries[$code];
	}

	if (!empty($name)) {
		$name = ucwords($name);
		return $countries[$name];
	}
}

function __country_codes() {
	$countries = array(
		'<all>' => 'All Countries',
		'AF' => 'Afghanistan',
		'AX' => 'Aland Islands',
		'AL' => 'Albania',
		'DZ' => 'Algeria',
		'AS' => 'American Samoa',
		'AD' => 'Andorra',
		'AO' => 'Angola',
		'AI' => 'Anguilla',
		'AQ' => 'Antarctica',
		'AG' => 'Antigua And Barbuda',
		'AR' => 'Argentina',
		'AM' => 'Armenia',
		'AW' => 'Aruba',
		'AU' => 'Australia',
		'AT' => 'Austria',
		'AZ' => 'Azerbaijan',
		'BS' => 'Bahamas',
		'BH' => 'Bahrain',
		'BD' => 'Bangladesh',
		'BB' => 'Barbados',
		'BY' => 'Belarus',
		'BE' => 'Belgium',
		'BZ' => 'Belize',
		'BJ' => 'Benin',
		'BM' => 'Bermuda',
		'BT' => 'Bhutan',
		'BO' => 'Bolivia',
		'BA' => 'Bosnia And Herzegovina',
		'BW' => 'Botswana',
		'BV' => 'Bouvet Island',
		'BR' => 'Brazil',
		'IO' => 'British Indian Ocean Territory',
		'BN' => 'Brunei Darussalam',
		'BG' => 'Bulgaria',
		'BF' => 'Burkina Faso',
		'BI' => 'Burundi',
		'KH' => 'Cambodia',
		'CM' => 'Cameroon',
		'CA' => 'Canada',
		'CV' => 'Cape Verde',
		'KY' => 'Cayman Islands',
		'CF' => 'Central African Republic',
		'TD' => 'Chad',
		'CL' => 'Chile',
		'CN' => 'China',
		'CX' => 'Christmas Island',
		'CC' => 'Cocos (Keeling) Islands',
		'CO' => 'Colombia',
		'KM' => 'Comoros',
		'CG' => 'Congo',
		'CD' => 'Congo, Democratic Republic',
		'CK' => 'Cook Islands',
		'CR' => 'Costa Rica',
		'CI' => 'Cote D\'Ivoire',
		'HR' => 'Croatia',
		'CU' => 'Cuba',
		'CY' => 'Cyprus',
		'CZ' => 'Czech Republic',
		'DK' => 'Denmark',
		'DJ' => 'Djibouti',
		'DM' => 'Dominica',
		'DO' => 'Dominican Republic',
		'EC' => 'Ecuador',
		'EG' => 'Egypt',
		'SV' => 'El Salvador',
		'GQ' => 'Equatorial Guinea',
		'ER' => 'Eritrea',
		'EE' => 'Estonia',
		'ET' => 'Ethiopia',
		'FK' => 'Falkland Islands (Malvinas)',
		'FO' => 'Faroe Islands',
		'FJ' => 'Fiji',
		'FI' => 'Finland',
		'FR' => 'France',
		'GF' => 'French Guiana',
		'PF' => 'French Polynesia',
		'TF' => 'French Southern Territories',
		'GA' => 'Gabon',
		'GM' => 'Gambia',
		'GE' => 'Georgia',
		'DE' => 'Germany',
		'GH' => 'Ghana',
		'GI' => 'Gibraltar',
		'GR' => 'Greece',
		'GL' => 'Greenland',
		'GD' => 'Grenada',
		'GP' => 'Guadeloupe',
		'GU' => 'Guam',
		'GT' => 'Guatemala',
		'GG' => 'Guernsey',
		'GN' => 'Guinea',
		'GW' => 'Guinea-Bissau',
		'GY' => 'Guyana',
		'HT' => 'Haiti',
		'HM' => 'Heard Island & Mcdonald Islands',
		'VA' => 'Holy See (Vatican City State)',
		'HN' => 'Honduras',
		'HK' => 'Hong Kong',
		'HU' => 'Hungary',
		'IS' => 'Iceland',
		'IN' => 'India',
		'ID' => 'Indonesia',
		'IR' => 'Iran, Islamic Republic Of',
		'IQ' => 'Iraq',
		'IE' => 'Ireland',
		'IM' => 'Isle Of Man',
		'IL' => 'Israel',
		'IT' => 'Italy',
		'JM' => 'Jamaica',
		'JP' => 'Japan',
		'JE' => 'Jersey',
		'JO' => 'Jordan',
		'KZ' => 'Kazakhstan',
		'KE' => 'Kenya',
		'KI' => 'Kiribati',
		'KR' => 'Korea',
		'KW' => 'Kuwait',
		'KG' => 'Kyrgyzstan',
		'LA' => 'Lao People\'s Democratic Republic',
		'LV' => 'Latvia',
		'LB' => 'Lebanon',
		'LS' => 'Lesotho',
		'LR' => 'Liberia',
		'LY' => 'Libyan Arab Jamahiriya',
		'LI' => 'Liechtenstein',
		'LT' => 'Lithuania',
		'LU' => 'Luxembourg',
		'MO' => 'Macao',
		'MK' => 'Macedonia',
		'MG' => 'Madagascar',
		'MW' => 'Malawi',
		'MY' => 'Malaysia',
		'MV' => 'Maldives',
		'ML' => 'Mali',
		'MT' => 'Malta',
		'MH' => 'Marshall Islands',
		'MQ' => 'Martinique',
		'MR' => 'Mauritania',
		'MU' => 'Mauritius',
		'YT' => 'Mayotte',
		'MX' => 'Mexico',
		'FM' => 'Micronesia, Federated States Of',
		'MD' => 'Moldova',
		'MC' => 'Monaco',
		'MN' => 'Mongolia',
		'ME' => 'Montenegro',
		'MS' => 'Montserrat',
		'MA' => 'Morocco',
		'MZ' => 'Mozambique',
		'MM' => 'Myanmar',
		'NA' => 'Namibia',
		'NR' => 'Nauru',
		'NP' => 'Nepal',
		'NL' => 'Netherlands',
		'AN' => 'Netherlands Antilles',
		'NC' => 'New Caledonia',
		'NZ' => 'New Zealand',
		'NI' => 'Nicaragua',
		'NE' => 'Niger',
		'NG' => 'Nigeria',
		'NU' => 'Niue',
		'NF' => 'Norfolk Island',
		'MP' => 'Northern Mariana Islands',
		'NO' => 'Norway',
		'OM' => 'Oman',
		'PK' => 'Pakistan',
		'PW' => 'Palau',
		'PS' => 'Palestinian Territory, Occupied',
		'PA' => 'Panama',
		'PG' => 'Papua New Guinea',
		'PY' => 'Paraguay',
		'PE' => 'Peru',
		'PH' => 'Philippines',
		'PN' => 'Pitcairn',
		'PL' => 'Poland',
		'PT' => 'Portugal',
		'PR' => 'Puerto Rico',
		'QA' => 'Qatar',
		'RE' => 'Reunion',
		'RO' => 'Romania',
		'RU' => 'Russian Federation',
		'RW' => 'Rwanda',
		'BL' => 'Saint Barthelemy',
		'SH' => 'Saint Helena',
		'KN' => 'Saint Kitts And Nevis',
		'LC' => 'Saint Lucia',
		'MF' => 'Saint Martin',
		'PM' => 'Saint Pierre And Miquelon',
		'VC' => 'Saint Vincent And Grenadines',
		'WS' => 'Samoa',
		'SM' => 'San Marino',
		'ST' => 'Sao Tome And Principe',
		'SA' => 'Saudi Arabia',
		'SN' => 'Senegal',
		'RS' => 'Serbia',
		'SC' => 'Seychelles',
		'SL' => 'Sierra Leone',
		'SG' => 'Singapore',
		'SK' => 'Slovakia',
		'SI' => 'Slovenia',
		'SB' => 'Solomon Islands',
		'SO' => 'Somalia',
		'ZA' => 'South Africa',
		'GS' => 'South Georgia And Sandwich Isl.',
		'ES' => 'Spain',
		'LK' => 'Sri Lanka',
		'SD' => 'Sudan',
		'SR' => 'Suriname',
		'SJ' => 'Svalbard And Jan Mayen',
		'SZ' => 'Swaziland',
		'SE' => 'Sweden',
		'CH' => 'Switzerland',
		'SY' => 'Syrian Arab Republic',
		'TW' => 'Taiwan',
		'TJ' => 'Tajikistan',
		'TZ' => 'Tanzania',
		'TH' => 'Thailand',
		'TL' => 'Timor-Leste',
		'TG' => 'Togo',
		'TK' => 'Tokelau',
		'TO' => 'Tonga',
		'TT' => 'Trinidad And Tobago',
		'TN' => 'Tunisia',
		'TR' => 'Turkey',
		'TM' => 'Turkmenistan',
		'TC' => 'Turks And Caicos Islands',
		'TV' => 'Tuvalu',
		'UG' => 'Uganda',
		'UA' => 'Ukraine',
		'AE' => 'United Arab Emirates',
		'GB' => 'United Kingdom',
		'US' => 'United States',
		'UM' => 'United States Outlying Islands',
		'UY' => 'Uruguay',
		'UZ' => 'Uzbekistan',
		'VU' => 'Vanuatu',
		'VE' => 'Venezuela',
		'VN' => 'Viet Nam',
		'VG' => 'Virgin Islands, British',
		'VI' => 'Virgin Islands, U.S.',
		'WF' => 'Wallis And Futuna',
		'EH' => 'Western Sahara',
		'YE' => 'Yemen',
		'ZM' => 'Zambia',
		'ZW' => 'Zimbabwe',
	);

	return $countries;
}

