core = 7.x
api = 2

; Modules
projects[] = "admin_menu"
projects[] = "module_filter"
projects[] = "auto_nodetitle"
projects[] = "ctools"
projects[] = "cck"
projects[] = "ckeditor"
projects[] = "content_taxonomy"
projects[] = "custom_search"
projects[] = "data"
projects[] = "date"
projects[] = "db_maintenance"
projects[] = "entity"
projects[] = "features"
projects[] = "feeds"
projects[] = "feeds_tamper"
projects[] = "field_group"
projects[] = "filefield_paths"
projects[] = "glossify"
projects[] = "google_analytics"
projects[] = "htaccess"
projects[] = "i18n"
projects[] = "indexpage"
projects[] = "job_scheduler"
projects[] = "jquery_ui"
projects[] = "jquery_update"
projects[] = "libraries"
projects[] = "multiupload_filefield_widget"
projects[] = "references"
projects[] = "nodeblock"
projects[] = "nodequeue"
projects[] = "options_element"
projects[] = "pathauto"
projects[] = "robotstxt"
projects[] = "services"
projects[] = "simplehtmldom"
projects[] = "token"
projects[] = "variable"
projects[] = "xmlsitemap"
projects[] = "oauth"

; Themes
projects[] = "boilerplate"
